proxy:
  endpoints:
    # Existing GitHub API endpoint
    /github-api:
      target: https://api.github.com
      pathRewrite:
        /api/proxy/github-api/?: /
      headers:
        Authorization: token ${PROXY_GITHUB_TOKEN}

    /github-raw:
      target: https://raw.githubusercontent.com
      pathRewrite:
        "/api/proxy/github-raw/?": ""
      headers:
        Authorization: token ${PROXY_GITHUB_TOKEN}        