# Updated Proxy Configuration for Harness IDP
# Add this to your Harness IDP proxy configuration

proxy:
  endpoints:
    # GitHub API endpoint for dynamic data loading
    /github-api:
      target: https://api.github.com
      pathRewrite:
        "^/proxy/github-api": ""
      headers:
        Authorization: token ${GITHUB_TOKEN}
        Accept: application/vnd.github.v3+json
        User-Agent: Harness-IDP-AWS-Access

    # GitHub Raw Content endpoint for direct file access
    /github-raw:
      target: https://raw.githubusercontent.com
      pathRewrite:
        "^/proxy/github-raw": ""
      headers:
        User-Agent: Harness-IDP-AWS-Access